### ISSUE TITLE
UnhandledPromiseRejectionWarning for invalid protocol: https

### ISSUE THREAD

**Issue by cyc115** [ravgeetdhillon/notion-feeder#13]
```
Fetching feed items from  https://cloudseclist.com/feed.xml 
(node:1575) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (internal/errors.js:322:7)
    at new ClientRequest (_http_client.js:159:11)
    at request (http.js:94:10)
    at get (http.js:105:15)
    at /home/runner/work/notion-feeder/notion-feeder/index.js:35808:17
    at new Promise (<anonymous>)
    at Parser.parseURL (/home/runner/work/notion-feeder/notion-feeder/index.js:35806:16)
    at getNewFeedItemsFrom (/home/runner/work/notion-feeder/notion-feeder/index.js:48219:28)
    at getNewFeedItems (/home/runner/work/notion-feeder/notion-feeder/index.js:48239:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by ravgeetdhillon** [comment]
@cyc115 I have just pushed an update that should resolve this error.

**Comment by ravgeetdhillon** [comment]
This issue has been solved in the latest updates.
